services:
  - type: web
    name: mandapx-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        value: https://mandapx.vercel.app
